# --- Base Stage ---
FROM node:20-alpine AS base
WORKDIR /app
RUN npm install -g pnpm@latest
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
ENV NODE_ENV=production
COPY . .
RUN pnpm build

# --- Production Stage ---
FROM nginx:alpine AS prod
WORKDIR /usr/share/nginx/html
COPY --from=base /app/dist ./
COPY ./news-aggregator.nginx.conf /etc/nginx/sites-enabled/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

